# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('primary_phone', models.CharField(max_length=13)),
                ('secondary_phone', models.CharField(blank=True, max_length=13)),
                ('birth_date', models.DateField()),
                ('status', models.CharField(choices=[('UP', 'Unregistered Player'), ('FA', 'Free Agent'), ('AP', 'Assigned Player')], max_length=2)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
