# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_goals', models.PositiveIntegerField()),
                ('away_goals', models.PositiveIntegerField()),
                ('winner', models.CharField(max_length=4)),
                ('overtime', models.BooleanField(default=False)),
                ('shootout', models.BooleanField(default=False)),
                ('game_length', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerplay_goal', models.BooleanField(default=False)),
                ('shorthanded_goal', models.BooleanField(default=False)),
                ('game_winning_goal', models.BooleanField(default=False)),
                ('overtime_goal', models.BooleanField(default=False)),
                ('assist_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_assist_first', to='player.Player')),
                ('assist_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_assist_second', to='player.Player')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Game')),
                ('goal_scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_goal_scorer', to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('plus_minus', models.IntegerField()),
                ('shots', models.PositiveIntegerField()),
                ('time_on_ice', models.TimeField()),
                ('penalties_in_minutes', models.TimeField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Division')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.PositiveIntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_away', to='league.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='division_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Division'),
        ),
        migrations.AddField(
            model_name='game',
            name='first_star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_first_star', to='player.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_home', to='league.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='second_star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_second_star', to='player.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='third_star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_third_star', to='player.Player'),
        ),
        migrations.AddField(
            model_name='division',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season'),
        ),
        migrations.AlterUniqueTogether(
            name='teamroster',
            unique_together=set([('team_id', 'player_number'), ('team_id', 'player_id')]),
        ),
    ]
